#端口
server:
  port: 9000
#应用名
spring:
  application:
    name: gateway
  #注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #register-enabled: true
    # 网关
    gateway:
      discovery:
        locator:
          #lowerCaseServiceId: true
          enabled: true
#      routes:
#        - id: lxytrans-consumer
#          uri: lb://client-3
#          predicates:
#            # Method 方法谓词，这里是匹配 GET 和 POST 请求
#            - Method=GET,POST