spring:
  profiles:
    active: dev
    include:
      - devv
  cache:
    type: ehcache
  application:
    name: xyy

  redis:
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最小空闲连接
        min-idle: 0


#????
server:
  port: 8081
  tomcat:
    #tomcat??????????????200
    max-threads: 500
    max-http-header-size: 20480
  undertow:
    #cpu????????С?2 ????IO?????, ???????з???????????,?????????????, ??????????CPU??????????
    io-threads: 8
    #io-threads*8 ????????????, ?????????servlet????????????, undertow??????????????????,?????????????????????
    worker-threads: 500
    max-http-post-size: 20480
  servlet:
    context-path: /demo

#spring.datasource:
#  name: ol5  #???????
#  url: jdbc:mysql://120.53.27.79:3306/ol5 #url
#  username: root  #?????
#  password: 271828  #????
#  driver-class-name: com.mysql.cj.jdbc.Driver  #?????????????

spring.datasource:
  name: testdatabase
  url: jdbc:postgresql://localhost:5432/testdatabase
  username: xyy
  password: 123456
  driver-class-name: org.postgresql.Driver


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xyy.test.entity
  #configuration:
  #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#Redis
spring.redis:
  database: 0
  host: 120.53.27.79
  port: 6379
  timeout: 5000



rocketmqaddr: localhost:9876

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring.cloud:
  nacos:
    discovery:
      server-addr: 127.0.0.1:8848

nacos:
  config:
    server-addr: 127.0.0.1:8848





